"""
SFEPY Thermal Solver Integration
================================

This module provides an interface to solve steady‑state thermal conduction
problems using the open‑source `SfePy <https://sfepy.org/>`_ finite element
analysis library.  While the native C solver in this project offers excellent
performance for structured grids, some users may wish to rely on a
well‑established external solver to gain confidence in the results or to
experiment with more advanced finite element formulations.  The class defined
here attempts to import the necessary parts of SfePy and, if available,
constructs a finite element problem that mirrors the thermal mesh generated
within this plugin.

**Limitations**
---------------

SfePy is not bundled with this repository.  If the package cannot be
imported at runtime, this solver will silently disable itself and the
``ThermalSolver`` will fall back to the native C solver or the pure Python
implementation.  Installing SfePy into the same Python environment as
KiCad is optional but highly recommended for those who wish to explore
finite element analysis workflows.

The current implementation focuses on steady‑state conduction and does not
include radiation or transient terms.  Those effects remain handled by the
native engine or the Python solver.  Should you wish to extend SfePy to
include these phenomena, the functions below provide a starting point for
defining additional boundary terms and time stepping schemes.

"""

from __future__ import annotations

import logging
from typing import Optional, Callable

try:
    # Lazy import of SfePy components.  If this fails, the solver
    # will remain unavailable and ``is_available`` will be False.
    from sfepy.discrete import Problem
    from sfepy.discrete.fem import Mesh, FEDomain, Field
    from sfepy.discrete.variables import FieldVariable
    from sfepy.discrete.materials import Material
    from sfepy.discrete.integrals import Integral
    from sfepy.terms import Term
    from sfepy.discrete.conditions import EssentialBC
    from sfepy.base.base import IndexedStruct
    HAS_SFEPY = True
except Exception:
    HAS_SFEPY = False

import numpy as np  # NumPy is required for constructing the mesh

from .thermal_solver import ThermalResult, ThermalMesh  # Reuse data classes
from ..core.constants import PhysicalConstants


class SfepyThermalSolver:
    """Solve steady‑state heat conduction using SfePy.

    This solver constructs a finite element mesh from the structured
    :class:`~tvac_thermal_analyzer.solvers.thermal_solver.ThermalMesh` and
    solves the Laplace equation with volumetric heat sources.  Fixed
    temperature nodes are enforced via Dirichlet boundary conditions.  The
    computed temperature field is mapped back onto the thermal mesh for
    visualisation in the KiCad plugin.

    If SfePy is not installed, the solver will report itself as unavailable
    and should not be selected by the :class:`~tvac_thermal_analyzer.solvers.thermal_solver.ThermalSolver`.
    """

    def __init__(self) -> None:
        self.logger = logging.getLogger(__name__)
        self.kelvin_offset = PhysicalConstants.CELSIUS_TO_KELVIN

    @property
    def is_available(self) -> bool:
        """Return ``True`` if SfePy was successfully imported."""
        return HAS_SFEPY

    @property
    def backend_name(self) -> str:
        return "SfePy" if HAS_SFEPY else "Unavailable"

    def solve_steady_state(
        self,
        mesh: ThermalMesh,
        ambient_temp_c: float = 25.0,
        chamber_wall_temp_c: float = 25.0,
        include_radiation: bool = False,
        convergence: float = 1e-6,
        max_iterations: int = 10000,
        progress_callback: Optional[Callable[[int, str], None]] = None,
    ) -> ThermalResult:
        """Solve the steady‑state conduction problem.

        Parameters
        ----------
        mesh: ThermalMesh
            The thermal mesh generated by :class:`~tvac_thermal_analyzer.solvers.mesh_gen.MeshGenerator`.
        ambient_temp_c: float, optional
            The initial temperature guess in Celsius.  All nodes are
            initialised to this temperature before solving.
        chamber_wall_temp_c: float, optional
            Ignored by the SfePy solver as radiation is not modelled.
        include_radiation: bool, optional
            Whether to include radiation.  Not yet supported in this solver.
        convergence: float, optional
            Convergence tolerance for iterative methods.  Ignored here as
            SfePy uses direct solvers by default.
        max_iterations: int, optional
            Maximum number of iterations.  Ignored in this solver.
        progress_callback: callable, optional
            Callback to report progress.  The percentage argument will
            increment from 0 to 100 during the solve.

        Returns
        -------
        ThermalResult
            Results object containing the temperature field on the mesh.
        """
        result = ThermalResult()

        if not HAS_SFEPY:
            result.converged = False
            result.error_message = (
                "SfepyThermalSolver: SfePy is not installed; "
                "install the 'sfepy' package to enable this solver."
            )
            return result

        # Build coordinate array (n_nodes, 3)
        num_nodes = mesh.nx * mesh.ny * mesh.nz
        if num_nodes != len(mesh.nodes):
            # The mesh must be fully populated
            result.converged = False
            result.error_message = "SfepyThermalSolver: inconsistent mesh dimensions"
            return result

        if progress_callback:
            progress_callback(5, "Constructing FE mesh")

        coors = np.zeros((num_nodes, 3), dtype=np.float64)
        for node in mesh.nodes:
            # Use metres for coordinates
            coors[node.node_id, 0] = node.x * 1e-3
            coors[node.node_id, 1] = node.y * 1e-3
            coors[node.node_id, 2] = node.z * 1e-3

        # Build connectivity for hexahedral elements.  Each cell in the
        # structured grid becomes one FE element.  The order of nodes in a
        # hexahedral element follows the convention used by SfePy:
        # [0, 1, 2, 3, 4, 5, 6, 7] corresponds to the bottom face in
        # counter‑clockwise order starting at the origin, then the top face.
        cells = []
        for iz in range(mesh.nz - 1):
            for iy in range(mesh.ny - 1):
                for ix in range(mesh.nx - 1):
                    n0 = mesh.get_node_index(ix,     iy,     iz    )
                    n1 = mesh.get_node_index(ix + 1, iy,     iz    )
                    n2 = mesh.get_node_index(ix + 1, iy + 1, iz    )
                    n3 = mesh.get_node_index(ix,     iy + 1, iz    )
                    n4 = mesh.get_node_index(ix,     iy,     iz + 1)
                    n5 = mesh.get_node_index(ix + 1, iy,     iz + 1)
                    n6 = mesh.get_node_index(ix + 1, iy + 1, iz + 1)
                    n7 = mesh.get_node_index(ix,     iy + 1, iz + 1)
                    cells.append([n0, n1, n2, n3, n4, n5, n6, n7])

        cells = np.array(cells, dtype=np.int32)
        # All elements belong to material group 1
        mat_ids = np.ones(len(cells), dtype=np.int32)
        # Create mesh
        femesh = Mesh.from_data('thermal_mesh', coors, None, [cells], [3], mat_ids)
        domain = FEDomain('thermal_domain', femesh)

        # Define approximation field
        field = Field.from_args('temperature', np.float64, 1, domain, approx_order=1)
        # Unknown and test variables
        T = FieldVariable('T', 'unknown', field, 0)
        s = FieldVariable('s', 'test', field, primary_var_name='T')

        # Thermal conductivity map.  For now we take the per‑node k and average
        # it for each element.  More advanced approaches could map k as a
        # function on each cell.
        cell_k = []
        for conn in cells:
            ks = [mesh.nodes[i].k for i in conn]
            # Avoid zero conductivity
            cell_k.append(float(sum(ks) / len(ks) or 0.29))
        k_vals = np.array(cell_k, dtype=np.float64)
        # SfePy expects material parameters shaped as (nel, 1, 1, 1)
        k_vals = k_vals[:, np.newaxis, np.newaxis, np.newaxis]
        m = Material('m', thermal_conductivity=k_vals)

        # Volumetric heat source q.  For each cell compute the sum of the
        # nodal heat sources divided by its volume.  SfePy expects shape
        # (nel, 1, 1, 1).
        cell_q = []
        for conn in cells:
            total_heat = sum(mesh.nodes[i].heat_source for i in conn)
            # Compute cell volume: use average of node volumes
            volumes = [mesh.nodes[i].volume for i in conn]
            vol = sum(volumes) / len(volumes) if volumes else 1.0
            # Power [W] -> volumetric power [W/m^3]
            q_val = (total_heat / max(vol, 1e-12))
            cell_q.append(q_val)
        q_vals = np.array(cell_q, dtype=np.float64)
        q_vals = q_vals[:, np.newaxis, np.newaxis, np.newaxis]
        q_mat = Material('q', heat_source=q_vals)

        # Define integral over elements
        integral = Integral('i', order=2)

        # Heat equation weak form: ∇·(k∇T) = −q
        # Implemented using dw_laplace for conduction and dw_volume_lvf for
        # volumetric heat sources.  Note the minus sign because SfePy
        # formulates the source on the right hand side.
        t_laplace = Term.new('dw_laplace(m.thermal_conductivity, s, T)', integral, domain, m=m, s=s, T=T)
        t_heat   = Term.new('dw_volume_lvf(q.heat_source, s)', integral, domain, q=q_mat, s=s)

        # Assemble equation
        equations = {'balance': t_laplace - t_heat}

        # Boundary conditions: apply fixed temperatures to nodes marked as
        # is_fixed_temp.  We collect the indices of those nodes and assign
        # their fixed temperature values (converted to Kelvin).
        dirichlet_idx = []
        dirichlet_val = []
        for node in mesh.nodes:
            if node.is_fixed_temp:
                dirichlet_idx.append(node.node_id)
                # Convert fixed temperature to Kelvin as SfePy uses the
                # physical values directly.  SfePy does not perform unit
                # conversions.
                dirichlet_val.append(node.fixed_temp + self.kelvin_offset)
        if dirichlet_idx:
            bc = EssentialBC('fixed', domain, dirichlet_idx, {'T.0': np.array(dirichlet_val)})
            ebcs = {'fixed': bc}
        else:
            ebcs = {}

        # Set up the problem
        pb = Problem('thermal', equations=equations)
        pb.set_bcs(ebcs=ebcs)

        # Use a direct linear solver.  SfePy internally decides based on
        # available packages (UMFPACK, MUMPS, etc.).
        # Solve for the temperature field
        if progress_callback:
            progress_callback(30, "Solving FE problem")
        try:
            state = pb.solve()
        except Exception as e:
            result.converged = False
            result.error_message = f"SfepyThermalSolver failed: {e}"
            return result

        # Extract temperatures at each node and convert back to Celsius.
        T_vals = state()['T']
        temperatures = []
        for val in T_vals:
            temperatures.append(float(val) - self.kelvin_offset)
        result.temperatures = temperatures
        result.min_temp = float(np.min(T_vals) - self.kelvin_offset)
        result.max_temp = float(np.max(T_vals) - self.kelvin_offset)
        result.avg_temp = float(np.mean(T_vals) - self.kelvin_offset)
        result.converged = True
        result.iterations = 1
        result.compute_time = 0.0  # Not tracked here
        return result

    # Transient analysis using SfePy is currently not implemented.  The
    # transient problem requires time stepping and potentially nonlinear
    # radiation boundary conditions.  Consider using the native engine or
    # extending SfePy with custom solvers.
